export interface ManufacturingSignal {
  signalId: string;
  category: "Machinery" | "Manpower" | "Materials" | "Money";
  phrases: string[];
}

export const manufacturingSignalLibrary: ManufacturingSignal[] = [

  { signalId: "machine_jam", category: "Machinery", phrases: ["machine jam", "machine jammed", "machine stuck", "jam event"] },
  { signalId: "micro_stoppage", category: "Machinery", phrases: ["micro stoppage", "micro-stoppage", "short stop", "brief stoppage", "minor stoppage"] },
  { signalId: "bearing_failure", category: "Machinery", phrases: ["bearing failure", "bearing worn", "bearing damage", "bearing replacement"] },
  { signalId: "motor_overheating", category: "Machinery", phrases: ["motor overheating", "motor overheat", "motor temperature", "motor heat"] },
  { signalId: "hydraulic_leak", category: "Machinery", phrases: ["hydraulic leak", "hydraulic failure", "hydraulic pressure drop", "oil leak"] },
  { signalId: "tool_wear", category: "Machinery", phrases: ["tool wear", "tool worn", "tool replacement", "tool life", "cutting tool degradation"] },
  { signalId: "machine_vibration", category: "Machinery", phrases: ["machine vibration", "excessive vibration", "vibration alarm", "vibration level"] },
  { signalId: "cycle_time_increase", category: "Machinery", phrases: ["cycle time increase", "cycle time longer", "slower cycle", "extended cycle time"] },
  { signalId: "changeover_delay", category: "Machinery", phrases: ["changeover delay", "changeover time", "slow changeover", "setup changeover"] },
  { signalId: "setup_time_increase", category: "Machinery", phrases: ["setup time increase", "longer setup", "extended setup", "setup delay"] },
  { signalId: "throughput_decline", category: "Machinery", phrases: ["throughput decline", "throughput drop", "reduced throughput", "output decline", "lower throughput"] },
  { signalId: "equipment_idle", category: "Machinery", phrases: ["equipment idle", "machine idle", "idle time", "machine waiting", "equipment waiting"] },
  { signalId: "machine_reset", category: "Machinery", phrases: ["machine reset", "equipment reset", "line reset", "system reset"] },
  { signalId: "sensor_fault", category: "Machinery", phrases: ["sensor fault", "sensor failure", "sensor malfunction", "faulty sensor", "sensor error"] },
  { signalId: "downtime", category: "Machinery", phrases: ["downtime", "machine downtime", "line downtime", "unplanned downtime", "equipment downtime"] },
  { signalId: "machine_breakdown", category: "Machinery", phrases: ["machine breakdown", "equipment breakdown", "breakdown event", "mechanical failure"] },
  { signalId: "line_stoppage", category: "Machinery", phrases: ["line stoppage", "line stop", "production line stop", "line halt"] },
  { signalId: "production_halt", category: "Machinery", phrases: ["production halt", "production stopped", "manufacturing halt"] },
  { signalId: "equipment_failure", category: "Machinery", phrases: ["equipment failure", "equipment malfunction", "machine failure", "system failure"] },
  { signalId: "calibration_drift", category: "Machinery", phrases: ["calibration drift", "out of calibration", "calibration error", "calibration overdue"] },
  { signalId: "pneumatic_fault", category: "Machinery", phrases: ["pneumatic fault", "pneumatic failure", "air pressure drop", "pneumatic leak"] },
  { signalId: "electrical_fault", category: "Machinery", phrases: ["electrical fault", "electrical failure", "wiring fault", "power surge"] },
  { signalId: "conveyor_fault", category: "Machinery", phrases: ["conveyor fault", "conveyor jam", "conveyor stoppage", "belt failure"] },
  { signalId: "plc_error", category: "Machinery", phrases: ["plc error", "plc fault", "controller error", "automation fault"] },
  { signalId: "oee_decline", category: "Machinery", phrases: ["oee decline", "oee drop", "low oee", "overall equipment effectiveness decline"] },

  { signalId: "pm_overdue", category: "Machinery", phrases: ["pm overdue", "preventive maintenance overdue", "scheduled maintenance overdue", "maintenance past due"] },
  { signalId: "maintenance_backlog", category: "Machinery", phrases: ["maintenance backlog", "maintenance queue", "pending maintenance", "overdue work orders"] },
  { signalId: "maintenance_delay", category: "Machinery", phrases: ["maintenance delay", "delayed maintenance", "late maintenance", "maintenance response time"] },
  { signalId: "emergency_repair", category: "Machinery", phrases: ["emergency repair", "urgent repair", "breakdown repair", "reactive repair", "unplanned repair"] },
  { signalId: "maintenance_cost_increase", category: "Money", phrases: ["maintenance cost increase", "rising maintenance cost", "repair cost increase", "maintenance expenditure"] },
  { signalId: "spare_part_shortage", category: "Materials", phrases: ["spare part shortage", "spare parts unavailable", "parts shortage", "no spare parts", "parts stockout"] },

  { signalId: "capacity_utilization_high", category: "Machinery", phrases: ["high capacity utilization", "over capacity", "capacity exceeded", "running at full capacity", "capacity strain"] },
  { signalId: "capacity_utilization_low", category: "Machinery", phrases: ["low capacity utilization", "under capacity", "underutilized", "idle capacity", "excess capacity"] },
  { signalId: "line_bottleneck", category: "Machinery", phrases: ["line bottleneck", "production bottleneck", "bottleneck station", "constraint station", "throughput bottleneck"] },
  { signalId: "schedule_instability", category: "Machinery", phrases: ["schedule instability", "unstable schedule", "schedule changes", "frequent rescheduling", "planning instability"] },
  { signalId: "production_delay", category: "Machinery", phrases: ["production delay", "manufacturing delay", "delayed production", "output delay"] },
  { signalId: "batch_size_change", category: "Machinery", phrases: ["batch size change", "lot size change", "smaller batches", "batch reduction"] },
  { signalId: "production_variance", category: "Machinery", phrases: ["production variance", "output variance", "production inconsistency", "output fluctuation"] },
  { signalId: "wip_buildup", category: "Machinery", phrases: ["wip buildup", "work in progress buildup", "wip accumulation", "high wip"] },
  { signalId: "takt_time_violation", category: "Machinery", phrases: ["takt time violation", "takt time exceeded", "missed takt", "takt breach"] },

  { signalId: "scrap_spike", category: "Materials", phrases: ["scrap spike", "scrap increase", "high scrap", "elevated scrap", "scrap surge"] },
  { signalId: "scrap_rate", category: "Materials", phrases: ["scrap rate", "scrap percentage", "scrap ratio", "material scrap rate"] },
  { signalId: "defect_rate", category: "Materials", phrases: ["defect rate", "defect percentage", "defect ratio", "high defects", "defective units"] },
  { signalId: "rework", category: "Materials", phrases: ["rework", "rework activity", "quality rework", "product rework", "rework loop"] },
  { signalId: "batch_rejection", category: "Materials", phrases: ["batch rejection", "batch rejected", "lot rejection", "rejected batch", "batch fail"] },
  { signalId: "quality_drift", category: "Materials", phrases: ["quality drift", "quality decline", "quality degradation", "quality inconsistency"] },
  { signalId: "tolerance_failure", category: "Materials", phrases: ["tolerance failure", "out of tolerance", "dimensional failure", "spec violation", "out of spec"] },
  { signalId: "inspection_failure", category: "Materials", phrases: ["inspection failure", "failed inspection", "qa rejection", "quality check failure"] },
  { signalId: "first_pass_yield_drop", category: "Materials", phrases: ["first pass yield drop", "fpy decline", "low first pass yield", "yield loss"] },
  { signalId: "contamination", category: "Materials", phrases: ["contamination", "contaminated material", "foreign material", "cross contamination"] },
  { signalId: "material_waste", category: "Materials", phrases: ["material waste", "excessive waste", "waste increase", "production waste"] },

  { signalId: "supplier_delay", category: "Materials", phrases: ["supplier delay", "supplier late", "vendor delay", "supplier delivery delay"] },
  { signalId: "leadtime_increase", category: "Materials", phrases: ["leadtime increase", "lead time increase", "longer lead time", "extended lead time"] },
  { signalId: "material_shortage", category: "Materials", phrases: ["material shortage", "raw material shortage", "material stockout", "material unavailable"] },
  { signalId: "material_variability", category: "Materials", phrases: ["material variability", "material inconsistency", "batch variation", "material quality variation"] },
  { signalId: "inventory_buildup", category: "Materials", phrases: ["inventory buildup", "excess inventory", "inventory surplus", "overstocking", "high inventory"] },
  { signalId: "inventory_shortage", category: "Materials", phrases: ["inventory shortage", "low inventory", "stockout", "stock shortage", "out of stock"] },
  { signalId: "delivery_delay", category: "Materials", phrases: ["delivery delay", "late delivery", "shipment delay", "dispatch delay", "delayed shipment"] },
  { signalId: "incoming_quality_issue", category: "Materials", phrases: ["incoming quality issue", "incoming material defect", "supplier quality issue", "receiving inspection failure"] },
  { signalId: "packaging_defect", category: "Materials", phrases: ["packaging defect", "packaging failure", "damaged packaging", "packaging issue"] },

  { signalId: "operator_fatigue", category: "Manpower", phrases: ["operator fatigue", "worker fatigue", "staff fatigue", "tired operators", "exhaustion"] },
  { signalId: "overtime_spike", category: "Manpower", phrases: ["overtime spike", "excessive overtime", "high overtime", "overtime increase", "overtime hours"] },
  { signalId: "extended_shift", category: "Manpower", phrases: ["extended shift", "extended shifts", "longer shifts", "shift extension", "12 hour shift"] },
  { signalId: "training_gap", category: "Manpower", phrases: ["training gap", "insufficient training", "untrained operator", "lack of training", "training deficiency"] },
  { signalId: "operator_error", category: "Manpower", phrases: ["operator error", "human error", "operator mistake", "manual error", "worker error"] },
  { signalId: "absenteeism", category: "Manpower", phrases: ["absenteeism", "absent workers", "staff absence", "high absenteeism", "unplanned absence"] },
  { signalId: "skill_shortage", category: "Manpower", phrases: ["skill shortage", "skilled worker shortage", "competency gap", "talent shortage", "skill deficit"] },
  { signalId: "high_turnover", category: "Manpower", phrases: ["high turnover", "staff turnover", "employee turnover", "attrition", "resignation"] },
  { signalId: "shift_handover_issue", category: "Manpower", phrases: ["shift handover issue", "poor shift handover", "handover gap", "shift transition error"] },
  { signalId: "supervision_gap", category: "Manpower", phrases: ["supervision gap", "lack of supervision", "unsupervised", "supervisory gap", "weak supervision"] },
  { signalId: "workforce_overload", category: "Manpower", phrases: ["workforce overload", "staff overload", "overworked", "excessive workload", "manpower strain"] },
  { signalId: "safety_incident", category: "Manpower", phrases: ["safety incident", "workplace injury", "accident", "near miss", "safety violation"] },
  { signalId: "morale_decline", category: "Manpower", phrases: ["morale decline", "low morale", "staff dissatisfaction", "employee disengagement"] },
  { signalId: "cross_training_gap", category: "Manpower", phrases: ["cross training gap", "single point of knowledge", "no backup operator", "key person dependency"] },
  { signalId: "communication_breakdown", category: "Manpower", phrases: ["communication breakdown", "miscommunication", "information gap", "poor communication"] },

  { signalId: "margin_erosion", category: "Money", phrases: ["margin erosion", "margin decline", "shrinking margins", "reduced margins", "profit margin drop"] },
  { signalId: "cost_overrun", category: "Money", phrases: ["cost overrun", "budget overrun", "over budget", "cost exceeded", "expenditure overrun"] },
  { signalId: "energy_cost_spike", category: "Money", phrases: ["energy cost spike", "energy cost increase", "high energy cost", "electricity cost", "utility cost increase"] },
  { signalId: "scrap_cost", category: "Money", phrases: ["scrap cost", "cost of scrap", "waste cost", "material loss cost"] },
  { signalId: "rework_cost", category: "Money", phrases: ["rework cost", "cost of rework", "rework expenditure", "quality cost"] },
  { signalId: "overtime_cost", category: "Money", phrases: ["overtime cost", "overtime expenditure", "overtime pay", "overtime expense"] },
  { signalId: "warranty_cost", category: "Money", phrases: ["warranty cost", "warranty claims", "warranty expense", "warranty returns"] },
  { signalId: "revenue_decline", category: "Money", phrases: ["revenue decline", "revenue drop", "sales decline", "revenue loss"] },
  { signalId: "cash_flow_pressure", category: "Money", phrases: ["cash flow pressure", "cash flow strain", "cash flow issue", "liquidity pressure"] },
  { signalId: "capital_underutilization", category: "Money", phrases: ["capital underutilization", "poor roi", "low return on investment", "asset underperformance"] },
  { signalId: "penalty_cost", category: "Money", phrases: ["penalty cost", "late delivery penalty", "contract penalty", "service level penalty"] },
  { signalId: "otd_decline", category: "Money", phrases: ["otd decline", "on time delivery decline", "late delivery", "delivery performance drop", "missed delivery"] },
  { signalId: "cost_per_unit_increase", category: "Money", phrases: ["cost per unit increase", "rising unit cost", "higher production cost", "manufacturing cost increase"] },
  { signalId: "inventory_carrying_cost", category: "Money", phrases: ["inventory carrying cost", "holding cost", "storage cost", "warehousing cost"] },
  { signalId: "freight_cost_increase", category: "Money", phrases: ["freight cost increase", "shipping cost increase", "logistics cost", "transport cost increase"] },
  { signalId: "labor_cost_increase", category: "Money", phrases: ["labor cost increase", "rising labor cost", "wage increase", "manpower cost increase"] },

  { signalId: "repair_activity", category: "Machinery", phrases: ["repair activity", "repair work", "corrective repair", "equipment repair"] },
  { signalId: "lubrication_issue", category: "Machinery", phrases: ["lubrication issue", "lubrication failure", "dry bearing", "insufficient lubrication"] },
  { signalId: "alignment_issue", category: "Machinery", phrases: ["alignment issue", "misalignment", "shaft misalignment", "belt misalignment"] },
  { signalId: "cooling_system_fault", category: "Machinery", phrases: ["cooling system fault", "cooling failure", "overheating", "coolant issue"] },
  { signalId: "power_fluctuation", category: "Machinery", phrases: ["power fluctuation", "voltage fluctuation", "power instability", "power outage"] },
  { signalId: "die_wear", category: "Machinery", phrases: ["die wear", "mold wear", "die damage", "tooling degradation"] },
  { signalId: "filter_clog", category: "Machinery", phrases: ["filter clog", "clogged filter", "filter blockage", "filter replacement overdue"] },
  { signalId: "compressor_fault", category: "Machinery", phrases: ["compressor fault", "compressor failure", "air compressor issue", "compressor breakdown"] },

  { signalId: "demand_volatility", category: "Money", phrases: ["demand volatility", "demand fluctuation", "unstable demand", "erratic demand"] },
  { signalId: "forecast_inaccuracy", category: "Money", phrases: ["forecast inaccuracy", "inaccurate forecast", "forecast error", "demand forecast miss"] },
  { signalId: "customer_complaint", category: "Money", phrases: ["customer complaint", "customer rejection", "client complaint", "quality complaint"] },
  { signalId: "order_cancellation", category: "Money", phrases: ["order cancellation", "cancelled order", "order withdrawal", "lost order"] },

];
