export const manufacturingMappings: Record<string, string[]> = {
  "alarm frequency": ["mfg-alarm-fatigue"],
  "asset utilization low": ["mfg-utilization-loss","mfg-machine-utilization-imbalance","mfg-scheduling-allocation-gap","mfg-capital-utilization"],
  "batch rejection": ["mfg-defect-containment-failure"],
  "calibration drift": ["mfg-machine-calibration-drift"],
  "capacity constraint": ["mfg-capacity-bottleneck","mfg-line-balancing-failure","mfg-machine-throughput-constraint","mfg-workstation-overload","mfg-machine-utilization-imbalance","mfg-product-mix-constraint","mfg-rework-capacity-consumption","mfg-investment-timing-gap"],
  "capacity loss cost": ["mfg-overhead-absorption-failure"],
  "changeover delay": ["mfg-batch-size-inefficiency","mfg-changeover-inefficiency","mfg-changeover-preparation-gap","mfg-tooling-availability","mfg-product-mix-constraint"],
  "cogs increase": ["mfg-hidden-cost-accumulation","mfg-cost-structure","mfg-material-cost-escalation"],
  "communication breakdown": ["mfg-shift-handover-failure"],
  "component defect": ["mfg-quality-defect","mfg-specification-misalignment"],
  "compressed air issue": ["mfg-compressed-air-waste"],
  "cross training gap": ["mfg-multi-skill-shortage"],
  "cycle time variance": ["mfg-process-cycle-time-imbalance","mfg-line-balancing","mfg-takt-time-mismatch"],
  "depreciation impact": ["mfg-depreciation-vs-output"],
  "discipline issue": ["mfg-supervision-gap"],
  "downtime": ["mfg-maintenance-scheduling-failure","mfg-equipment-aging","mfg-changeover-inefficiency","mfg-availability-loss","mfg-idle-energy-consumption"],
  "downtime spike": ["mfg-unplanned-downtime"],
  "electrical fault": ["mfg-electrical-system-failure"],
  "energy cost spike": ["mfg-energy-cost-spike","mfg-energy-waste-equipment","mfg-idle-energy-consumption","mfg-compressed-air-waste"],
  "ergonomic issue": ["mfg-ergonomic-strain"],
  "extended shifts": ["mfg-workforce-overload","mfg-break-schedule-inadequacy"],
  "fixture issue": ["mfg-tooling-availability"],
  "frequent adjustments": ["mfg-microstoppages"],
  "high absenteeism": ["mfg-shift-coverage-gap"],
  "high production cost": ["mfg-pricing-cost-disconnect","mfg-energy-cost-spike","mfg-cost-structure","mfg-overhead-absorption-failure"],
  "hydraulic pressure loss": ["mfg-hydraulic-pneumatic-degradation"],
  "incoming quality failure": ["mfg-supplier-quality-inconsistency","mfg-quality-defect","mfg-inspection-failure"],
  "inventory buildup": ["mfg-demand-forecast-error"],
  "inventory carrying cost": ["mfg-spare-parts-inventory-cost"],
  "inventory count discrepancy": ["mfg-inventory-accuracy-gap"],
  "inventory shortage": ["mfg-material-shortage","mfg-demand-forecast-error","mfg-reorder-point-failure","mfg-inventory-accuracy-gap"],
  "knowledge loss": ["mfg-knowledge-retention-failure"],
  "labor cost ratio": ["mfg-labor-cost-productivity-gap"],
  "lead time increase": ["mfg-spare-parts-delay","mfg-obsolete-components","mfg-supplier-delay","mfg-supplier-capacity-limit","mfg-logistics-disruption"],
  "machine breakdown": ["mfg-maintenance-reactive","mfg-deferred-maintenance-risk","mfg-equipment-aging","mfg-reliability-degradation","mfg-failure-pattern-undetected"],
  "maintenance backlog": ["mfg-maintenance-reactive","mfg-maintenance-resource-shortage","mfg-maintenance-scheduling-failure","mfg-maintenance-backlog","mfg-pm-task-overload","mfg-maintenance-data-gap"],
  "maintenance cost increase": ["mfg-maintenance-cost","mfg-emergency-repair-premium","mfg-contractor-dependency-cost"],
  "maintenance overdue": ["mfg-pm-compliance-failure","mfg-pm-task-overload"],
  "margin erosion": ["mfg-margin-erosion","mfg-hidden-cost-accumulation"],
  "margin pressure": ["mfg-margin-erosion","mfg-pricing-cost-disconnect"],
  "material cost increase": ["mfg-material-cost-escalation"],
  "material feed issue": ["mfg-material-feed-stoppage"],
  "material shortage": ["mfg-material-shortage","mfg-reorder-point-failure","mfg-single-source-dependency"],
  "material waste": ["mfg-material-waste-excess"],
  "micro stoppage": ["mfg-performance-loss","mfg-microstoppages","mfg-sensor-reliability-issue","mfg-material-feed-stoppage","mfg-alarm-fatigue"],
  "morale issue": ["mfg-team-conflict-impact"],
  "new operator issue": ["mfg-new-operator-integration"],
  "night shift fatigue": ["mfg-night-shift-fatigue"],
  "oee decline": ["mfg-speed-loss-aging","mfg-utilization-loss","mfg-energy-waste-equipment"],
  "operator error": ["mfg-operator-fatigue","mfg-night-shift-fatigue","mfg-skill-gap","mfg-new-operator-integration","mfg-work-instruction-gap","mfg-training-effectiveness"],
  "operator fatigue": ["mfg-work-element-imbalance","mfg-operator-fatigue","mfg-ergonomic-strain","mfg-break-schedule-inadequacy"],
  "operator shortage": ["mfg-staffing-shortage","mfg-shift-coverage-gap"],
  "overtime cost": ["mfg-overtime-dependency","mfg-labor-cost-productivity-gap"],
  "overtime spike": ["mfg-capacity-bottleneck","mfg-workstation-overload","mfg-workforce-overload","mfg-overtime-dependency","mfg-production-schedule-instability"],
  "plc error": ["mfg-electrical-system-failure"],
  "pm overdue": ["mfg-pm-compliance-failure","mfg-maintenance-backlog","mfg-maintenance-data-gap","mfg-deferred-maintenance-risk"],
  "pneumatic failure": ["mfg-hydraulic-pneumatic-degradation"],
  "process instability": ["mfg-process-control-variation","mfg-rework-root-cause-gap"],
  "quality deviation": ["mfg-process-change-training-lag","mfg-process-control-variation","mfg-machine-calibration-drift"],
  "receiving error": ["mfg-inspection-failure"],
  "recruitment difficulty": ["mfg-staffing-shortage"],
  "repair activity": ["mfg-maintenance-resource-shortage","mfg-breakdown-response-delay","mfg-contractor-dependency-cost"],
  "rework": ["mfg-quality-loss-oee","mfg-rework-cycle","mfg-rework-capacity-consumption","mfg-rework-traceability-gap"],
  "rework cost": ["mfg-waste-cost-visibility"],
  "rework rate high": ["mfg-rework-cycle","mfg-rework-root-cause-gap"],
  "roi decline": ["mfg-capital-utilization","mfg-depreciation-vs-output","mfg-investment-timing-gap"],
  "scrap": ["mfg-startup-quality-loss","mfg-quality-loss-oee","mfg-high-scrap-rate","mfg-material-waste-excess"],
  "scrap cost": ["mfg-waste-cost-visibility"],
  "scrap rate high": ["mfg-high-scrap-rate","mfg-yield-loss-pattern","mfg-defect-containment-failure"],
  "sensor failure": ["mfg-sensor-reliability-issue"],
  "shift handover issue": ["mfg-shift-handover-failure"],
  "skill gap": ["mfg-skill-gap","mfg-multi-skill-shortage","mfg-training-gap"],
  "spare parts cost": ["mfg-spare-parts-delay","mfg-obsolete-components","mfg-maintenance-cost","mfg-spare-parts-inventory-cost"],
  "specification deviation": ["mfg-specification-misalignment"],
  "speed loss": ["mfg-speed-loss-aging","mfg-machine-throughput-constraint","mfg-performance-loss"],
  "staff turnover": ["mfg-knowledge-retention-failure"],
  "startup loss": ["mfg-changeover-preparation-gap","mfg-startup-quality-loss"],
  "supervision gap": ["mfg-supervision-gap","mfg-supervisor-span-overload"],
  "supplier capacity issue": ["mfg-supplier-capacity-limit"],
  "supplier late delivery": ["mfg-single-source-dependency","mfg-supplier-delay","mfg-supplier-quality-inconsistency","mfg-logistics-disruption"],
  "team conflict": ["mfg-team-conflict-impact"],
  "traceability gap": ["mfg-rework-traceability-gap"],
  "training gap": ["mfg-training-gap","mfg-training-effectiveness","mfg-process-change-training-lag"],
  "unplanned downtime": ["mfg-breakdown-response-delay","mfg-availability-loss","mfg-unplanned-downtime","mfg-failure-pattern-undetected","mfg-emergency-repair-premium"],
  "wear detected": ["mfg-reliability-degradation"],
  "wip congestion": ["mfg-line-balancing-failure","mfg-process-cycle-time-imbalance","mfg-batch-size-inefficiency","mfg-line-balancing","mfg-takt-time-mismatch","mfg-work-element-imbalance","mfg-scheduling-allocation-gap"],
  "work instruction missing": ["mfg-work-instruction-gap"],
  "workload imbalance": ["mfg-production-schedule-instability","mfg-supervisor-span-overload"],
  "yield loss": ["mfg-yield-loss-pattern"],
};
