// ─────────────────────────────────────────────────────────────────────────────
// MGD PDF EXPORT — Premium Executive Operational Diagnostic Reports
//
// Generates boardroom-ready PDF reports from MGDReport objects using PDFKit.
// Seven pages: Cover → Summary → Benchmarks → Findings → Root Causes →
//              Recommendations → Narrative.
//
// Design principles:
//   • Never throws — every page renderer wrapped in try/catch with graceful fallback.
//   • All text passed through safeText() to prevent null/undefined rendering.
//   • severityColor() and priorityColor() provide consistent visual language.
//   • Page numbers and footer on every page via addFooter().
//   • [MGD][PDF] prefix on all log lines.
// ─────────────────────────────────────────────────────────────────────────────

import PDFDocument from "pdfkit";
import type { MGDReport }              from "./report-composer";
import type { OperationalFinding }     from "./findings-engine";
import type { RootCause }              from "./root-cause-engine";
import type { OperationalRecommendation } from "./recommendation-engine";
import type { BenchmarkResult }        from "./benchmark-engine";

// ── Design tokens ─────────────────────────────────────────────────────────────

const C = {
  ink:        "#0f172a",   // near-black — headings
  body:       "#334155",   // dark slate — body text
  muted:      "#64748b",   // muted — captions, secondary
  light:      "#94a3b8",   // light — rules, labels
  rule:       "#e2e8f0",   // separator lines
  pageBg:     "#f8fafc",   // page background tint (unused in PDFKit but noted)

  // Cover / section headers
  coverBg:    "#0f172a",
  coverText:  "#f8fafc",
  coverMuted: "#94a3b8",

  // Accent
  accent:     "#1e40af",   // executive navy
  accentText: "#ffffff",

  // Severity
  critical:   "#dc2626",
  high:       "#ea580c",
  medium:     "#d97706",
  low:        "#2563eb",
  healthy:    "#16a34a",
  watchlist:  "#d97706",
  elevated:   "#ea580c",

  // Section header background
  sectionBg:  "#1e293b",
};

const F = {
  regular:    "Helvetica",
  bold:       "Helvetica-Bold",
  oblique:    "Helvetica-Oblique",
};

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y  = PAGE_H - 36;

const TIMEFRAME_LABELS: Record<string, string> = {
  IMMEDIATE: "Immediate",
  "30_DAYS": "30 Days",
  "90_DAYS": "90 Days",
  LONG_TERM: "Long Term",
};

const TIMEFRAME_ORDER = ["IMMEDIATE", "30_DAYS", "90_DAYS", "LONG_TERM"];

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Coerce any value to a safe non-empty string. */
export function safeText(v: unknown, fallback = "—"): string {
  if (v == null) return fallback;
  const s = String(v).trim();
  return s.length > 0 ? s : fallback;
}

/** Truncate text to a max length with ellipsis. */
function trunc(text: string, max: number): string {
  const s = safeText(text);
  return s.length > max ? s.slice(0, max - 1) + "…" : s;
}

/** Severity → color hex. */
export function severityColor(severity: string): string {
  const s = (severity ?? "").toUpperCase();
  if (s === "CRITICAL") return C.critical;
  if (s === "HIGH")     return C.high;
  if (s === "MEDIUM")   return C.medium;
  return C.low;
}

/** Priority → color hex (same mapping as severity). */
export function priorityColor(priority: string): string {
  return severityColor(priority);
}

/** Benchmark status → color hex. */
function benchmarkColor(status: string): string {
  const s = (status ?? "").toUpperCase();
  if (s === "CRITICAL") return C.critical;
  if (s === "ELEVATED") return C.elevated;
  if (s === "WATCHLIST")return C.watchlist;
  return C.healthy;
}

// ── Layout helpers ─────────────────────────────────────────────────────────────

/** Draw a thin horizontal rule. */
function rule(doc: PDFKit.PDFDocument, y: number, color = C.rule): void {
  doc.save()
    .strokeColor(color).lineWidth(0.5)
    .moveTo(MARGIN, y).lineTo(MARGIN + CONTENT_W, y).stroke()
    .restore();
}

/** Fill a rectangle. */
function fillRect(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, color: string): void {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

/** Render the standard footer with page number on the current page. */
function addFooter(doc: PDFKit.PDFDocument, pageNum: number, totalPages: number): void {
  doc.save();
  rule(doc, FOOTER_Y - 4, C.rule);
  doc.font(F.regular).fontSize(7).fillColor(C.light)
    .text("Generated by MGD Operational Intelligence · Scope Optix Sdn. Bhd. · Confidential",
      MARGIN, FOOTER_Y, { width: CONTENT_W - 60, align: "left" });
  doc.font(F.regular).fontSize(7).fillColor(C.light)
    .text(`Page ${pageNum} of ${totalPages}`,
      MARGIN, FOOTER_Y, { width: CONTENT_W, align: "right" });
  doc.restore();
}

/** Draw a small filled severity pill badge. Returns its rendered width. */
function severityBadge(doc: PDFKit.PDFDocument, x: number, y: number, label: string, color: string): number {
  const txt = safeText(label);
  const tw = doc.font(F.bold).fontSize(7).widthOfString(txt);
  const pw = tw + 10;
  const ph = 12;
  doc.save()
    .roundedRect(x, y - 1, pw, ph, 3).fill(color);
  doc.fillColor("#ffffff").font(F.bold).fontSize(7)
    .text(txt, x + 5, y + 1, { lineBreak: false });
  doc.restore();
  return pw + 6;
}

/** Render a mini progress/confidence bar. */
function confBar(doc: PDFKit.PDFDocument, x: number, y: number, w: number, pct: number, color: string): void {
  doc.save()
    .roundedRect(x, y, w, 5, 2).fillColor(C.rule).fill()
    .roundedRect(x, y, Math.max(4, w * (pct / 100)), 5, 2).fillColor(color).fill()
    .restore();
}

/** Print a labelled key–value row. Returns new y offset. */
function kvRow(doc: PDFKit.PDFDocument, x: number, y: number, label: string, value: string, w = CONTENT_W): number {
  doc.font(F.bold).fontSize(8).fillColor(C.muted)
    .text(safeText(label).toUpperCase(), x, y, { width: 130 });
  doc.font(F.regular).fontSize(8).fillColor(C.body)
    .text(safeText(value), x + 135, y, { width: w - 135 });
  return y + 13;
}

// ── Page renderers ─────────────────────────────────────────────────────────────

// PAGE 1 — Executive Cover ─────────────────────────────────────────────────────

function renderCover(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const { metadata, visualMetrics, summary } = report;
  const score = metadata.operationalHealthScore;

  // Dark header block — full width, 340pt tall
  fillRect(doc, 0, 0, PAGE_W, 340, C.coverBg);

  // Firm line
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text("SCOPE OPTIX SDN. BHD.", MARGIN, 38, { characterSpacing: 2 });

  // Title
  doc.font(F.bold).fontSize(24).fillColor(C.coverText)
    .text("Operational Diagnostic Report", MARGIN, 58, { width: CONTENT_W - 120 });

  // Subtitle
  doc.font(F.regular).fontSize(11).fillColor(C.coverMuted)
    .text("Margin Guard Diagnostics — MGD Operational Intelligence", MARGIN, 92, { width: CONTENT_W - 120 });

  // Version badge
  fillRect(doc, MARGIN, 115, 62, 16, "#1e3a5f");
  doc.font(F.bold).fontSize(8).fillColor("#7dd3fc")
    .text(safeText(metadata.reportVersion, "MGD-V1"), MARGIN + 6, 119);

  // Health score circle (right side)
  if (score != null) {
    const cx = PAGE_W - MARGIN - 60;
    const cy = 130;
    const r  = 52;

    // Outer ring
    doc.save().circle(cx, cy, r).strokeColor("#1e3a5f").lineWidth(2).stroke().restore();

    // Score
    doc.font(F.bold).fontSize(32).fillColor(C.coverText)
      .text(String(score), cx - r + 8, cy - 22, { width: r * 2 - 16, align: "center" });
    doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
      .text("/100", cx - r + 8, cy + 14, { width: r * 2 - 16, align: "center" });
    doc.font(F.regular).fontSize(7).fillColor(C.coverMuted)
      .text("HEALTH SCORE", cx - r + 8, cy + 28, { width: r * 2 - 16, align: "center", characterSpacing: 1 });
  }

  // Separator rule
  doc.save().strokeColor("#1e3a5f").lineWidth(0.5)
    .moveTo(MARGIN, 158).lineTo(MARGIN + CONTENT_W - (score != null ? 140 : 0), 158).stroke().restore();

  // Health label + risk level
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text(safeText(visualMetrics?.operationalHealthLabel, "Assessment Pending"), MARGIN, 170, { width: CONTENT_W - 160 });

  doc.font(F.regular).fontSize(9).fillColor(C.coverMuted)
    .text(`Operational Risk Level: ${safeText(visualMetrics?.operationalRiskLevel)}`, MARGIN, 193, { width: CONTENT_W - 160 });

  // Client block
  doc.font(F.bold).fontSize(10).fillColor(C.coverText)
    .text(safeText(metadata.clientName, "Client — Confidential Report"), MARGIN, 220, { width: CONTENT_W - 50 });

  if (metadata.industry) {
    doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
      .text(metadata.industry.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase()), MARGIN, 236);
  }

  // Generated date
  const genDate = new Date(metadata.generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(`Report generated: ${genDate}`, MARGIN, 254);

  // Quick-stat strip inside cover block
  const stats = [
    { label: "Critical Findings",    value: String(summary?.criticalFindings ?? 0),            color: C.critical },
    { label: "Critical Root Causes", value: String(summary?.criticalRootCauses ?? 0),           color: C.critical },
    { label: "Priority Actions",     value: String(summary?.highPriorityRecommendations ?? 0),  color: C.accent },
    { label: "Benchmark Alerts",     value: String(summary?.benchmarkAlerts ?? 0),              color: C.elevated },
  ];
  const statW = CONTENT_W / stats.length;
  stats.forEach((s, i) => {
    const sx = MARGIN + i * statW;
    const sy = 287;
    fillRect(doc, sx, sy, statW - 4, 42, "#1a2744");
    doc.font(F.bold).fontSize(20).fillColor(s.color)
      .text(s.value, sx + 8, sy + 6, { width: statW - 20 });
    doc.font(F.regular).fontSize(7).fillColor(C.coverMuted)
      .text(s.label, sx + 8, sy + 30, { width: statW - 16 });
  });

  // Below cover block — confidential note
  doc.font(F.oblique).fontSize(8).fillColor(C.muted)
    .text("This report is prepared exclusively for the named client. All information is confidential and proprietary.", MARGIN, 358, { width: CONTENT_W });
}

// PAGE 2 — Executive Summary ──────────────────────────────────────────────────

function renderSummary(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const { summary, visualMetrics, metadata } = report;
  const bsd = visualMetrics?.benchmarkStatusBreakdown ?? { healthy: 0, watchlist: 0, elevated: 0, critical: 0 };

  // Section header
  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Executive Summary", MARGIN, MARGIN + 2);
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(safeText(metadata.clientName), PAGE_W - MARGIN - 160, MARGIN + 5, { width: 160, align: "right" });

  let y = MARGIN + 50;

  // Summary metric boxes — 2 rows of 3
  const boxes = [
    { label: "Critical Findings",          value: summary?.criticalFindings ?? 0,             color: C.critical },
    { label: "High Findings",              value: summary?.highFindings ?? 0,                  color: C.high },
    { label: "Critical Root Causes",       value: summary?.criticalRootCauses ?? 0,            color: C.critical },
    { label: "Priority Recommendations",   value: summary?.highPriorityRecommendations ?? 0,   color: C.accent },
    { label: "Benchmark Alerts",           value: summary?.benchmarkAlerts ?? 0,               color: C.elevated },
    { label: "Operational Health",         value: metadata?.operationalHealthScore != null ? `${metadata.operationalHealthScore}/100` : "N/A", color: C.ink },
  ];
  const boxW = (CONTENT_W - 10) / 3;
  const boxH = 58;

  boxes.forEach((b, i) => {
    const row = Math.floor(i / 3);
    const col = i % 3;
    const bx = MARGIN + col * (boxW + 5);
    const by = y + row * (boxH + 6);

    fillRect(doc, bx, by, boxW, boxH, "#f8fafc");
    doc.save().rect(bx, by, boxW, boxH).strokeColor(C.rule).lineWidth(0.5).stroke().restore();
    // Left accent bar
    fillRect(doc, bx, by, 3, boxH, b.color);

    doc.font(F.bold).fontSize(22).fillColor(b.color)
      .text(String(b.value), bx + 10, by + 8, { width: boxW - 16 });
    doc.font(F.regular).fontSize(8).fillColor(C.muted)
      .text(b.label, bx + 10, by + 40, { width: boxW - 16 });
  });

  y += 2 * (boxH + 6) + 20;
  rule(doc, y);
  y += 14;

  // Benchmark breakdown bar
  doc.font(F.bold).fontSize(9).fillColor(C.ink)
    .text("BENCHMARK STATUS BREAKDOWN", MARGIN, y, { characterSpacing: 0.5 });
  y += 16;

  const bmItems = [
    { label: "Critical",  count: bsd.critical,  color: C.critical },
    { label: "Elevated",  count: bsd.elevated,  color: C.elevated },
    { label: "Watchlist", count: bsd.watchlist, color: C.watchlist },
    { label: "Healthy",   count: bsd.healthy,   color: C.healthy },
  ];
  const total = bmItems.reduce((s, b) => s + b.count, 0) || 1;
  let barX = MARGIN;
  const barH = 14;
  bmItems.forEach(b => {
    const bw = Math.max(0, (b.count / total) * CONTENT_W);
    if (bw > 0) {
      fillRect(doc, barX, y, bw, barH, b.color);
      barX += bw;
    }
  });
  y += barH + 8;

  // Legend
  let lx = MARGIN;
  bmItems.forEach(b => {
    fillRect(doc, lx, y + 2, 8, 8, b.color);
    doc.font(F.regular).fontSize(8).fillColor(C.body)
      .text(`${b.label} (${b.count})`, lx + 12, y, { lineBreak: false });
    lx += doc.widthOfString(`${b.label} (${b.count})`) + 26;
  });

  y += 24;
  rule(doc, y);
  y += 14;

  // Health classification note
  doc.font(F.bold).fontSize(9).fillColor(C.ink)
    .text("OPERATIONAL HEALTH CLASSIFICATION", MARGIN, y, { characterSpacing: 0.5 });
  y += 14;

  const classifications = [
    { range: "≥ 80", label: "Operationally Stable",       color: C.healthy },
    { range: "65–79",label: "Moderate Operational Strain", color: C.watchlist },
    { range: "50–64",label: "Elevated Operational Strain", color: C.elevated },
    { range: "< 50", label: "Critical Operational Instability", color: C.critical },
  ];

  const score = metadata?.operationalHealthScore;
  classifications.forEach(cl => {
    const isCurrent =
      score != null && (
        (cl.range === "≥ 80"  && score >= 80) ||
        (cl.range === "65–79" && score >= 65 && score < 80) ||
        (cl.range === "50–64" && score >= 50 && score < 65) ||
        (cl.range === "< 50"  && score < 50)
      );

    if (isCurrent) fillRect(doc, MARGIN - 2, y - 1, CONTENT_W + 4, 14, "#f0f9ff");
    fillRect(doc, MARGIN, y + 2, 8, 8, cl.color);
    doc.font(isCurrent ? F.bold : F.regular).fontSize(8).fillColor(isCurrent ? cl.color : C.body)
      .text(`${cl.range}  —  ${cl.label}`, MARGIN + 14, y, { lineBreak: false });
    if (isCurrent) {
      doc.font(F.bold).fontSize(7).fillColor(cl.color)
        .text("  ◀ Current", MARGIN + 14 + doc.widthOfString(`${cl.range}  —  ${cl.label}`), y, { lineBreak: false });
    }
    y += 14;
  });
}

// PAGE 3 — Benchmark Overview ──────────────────────────────────────────────────

function renderBenchmarks(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const benchmarks = Array.isArray(report.benchmarks) ? report.benchmarks : [];

  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Benchmark Overview", MARGIN, MARGIN + 2);
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(`${benchmarks.length} metrics evaluated`, PAGE_W - MARGIN - 120, MARGIN + 5, { width: 120, align: "right" });

  let y = MARGIN + 44;

  if (benchmarks.length === 0) {
    doc.font(F.regular).fontSize(9).fillColor(C.muted).text("No benchmark data available.", MARGIN, y);
    return;
  }

  benchmarks.forEach((bm, i) => {
    if (y > FOOTER_Y - 80) return; // safety: don't overwrite footer

    const color = benchmarkColor(bm.status);
    const rowH  = 52;

    // Row background on alternating rows
    if (i % 2 === 0) fillRect(doc, MARGIN - 4, y - 4, CONTENT_W + 8, rowH, "#f8fafc");

    // Status badge
    severityBadge(doc, MARGIN, y, safeText(bm.status), color);

    // Metric name
    doc.font(F.bold).fontSize(9).fillColor(C.ink)
      .text(safeText(bm.metric), MARGIN + 70, y, { width: CONTENT_W - 70 });

    // Actual vs threshold
    doc.font(F.regular).fontSize(8).fillColor(C.muted)
      .text(`Actual: ${safeText(String(bm.actualValue))}  ·  Threshold: ${safeText(String(bm.benchmarkRange?.high))}`, MARGIN + 70, y + 12, { width: CONTENT_W - 70 });

    // Interpretation
    doc.font(F.regular).fontSize(8).fillColor(C.body)
      .text(trunc(safeText(bm.interpretation), 120), MARGIN + 70, y + 24, { width: CONTENT_W - 70 });

    // Confidence bar
    confBar(doc, MARGIN + 70, y + 40, 80, bm.confidence ?? 0, color);
    doc.font(F.regular).fontSize(7).fillColor(C.muted)
      .text(`${bm.confidence ?? 0}%`, MARGIN + 155, y + 38, { lineBreak: false });

    rule(doc, y + rowH - 2, "#f1f5f9");
    y += rowH + 2;
  });
}

// PAGE 4 — Key Findings ────────────────────────────────────────────────────────

function renderFindings(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const findings = Array.isArray(report.findings) ? report.findings : [];

  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Key Operational Findings", MARGIN, MARGIN + 2);
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(`${findings.length} finding${findings.length !== 1 ? "s" : ""} identified`, PAGE_W - MARGIN - 120, MARGIN + 5, { width: 120, align: "right" });

  let y = MARGIN + 44;

  if (findings.length === 0) {
    doc.font(F.regular).fontSize(9).fillColor(C.muted).text("No findings detected in this diagnostic run.", MARGIN, y);
    return;
  }

  findings.forEach((f, i) => {
    if (y > FOOTER_Y - 90) return;

    const color = severityColor(f.severity);
    const rowH  = 64;

    // Left accent bar
    fillRect(doc, MARGIN - 4, y - 2, 3, rowH - 2, color);

    // Index + severity badge
    doc.font(F.bold).fontSize(8).fillColor(C.muted)
      .text(String(i + 1).padStart(2, "0"), MARGIN + 4, y);
    severityBadge(doc, MARGIN + 22, y - 1, safeText(f.severity), color);

    // Category
    doc.font(F.regular).fontSize(7).fillColor(C.muted)
      .text(safeText(f.category).replace(/_/g, " ").toUpperCase(), MARGIN + 22 + 60, y, { characterSpacing: 0.3 });

    // Title
    doc.font(F.bold).fontSize(10).fillColor(C.ink)
      .text(trunc(safeText(f.title), 80), MARGIN, y + 14, { width: CONTENT_W - 90 });

    // Confidence bar (right side)
    doc.font(F.regular).fontSize(7).fillColor(C.muted)
      .text("Confidence", CONTENT_W - 30, y, { width: 80 });
    confBar(doc, CONTENT_W - 30, y + 12, 80, f.confidence ?? 0, color);
    doc.font(F.regular).fontSize(7).fillColor(color)
      .text(`${f.confidence ?? 0}%`, CONTENT_W - 30, y + 20, { width: 80 });

    // Summary
    doc.font(F.regular).fontSize(8).fillColor(C.body)
      .text(trunc(safeText(f.summary), 140), MARGIN, y + 28, { width: CONTENT_W - 95 });

    // Operational impact (first line only)
    const impact = Array.isArray(f.operationalImpact)
      ? (f.operationalImpact as string[])[0]
      : (typeof f.operationalImpact === "string" ? f.operationalImpact : null);
    if (impact) {
      doc.font(F.oblique).fontSize(7.5).fillColor(C.muted)
        .text(`Impact: ${trunc(impact, 100)}`, MARGIN, y + 50, { width: CONTENT_W - 30 });
    }

    rule(doc, y + rowH, "#f1f5f9");
    y += rowH + 4;
  });
}

// PAGE 5 — Root Causes ────────────────────────────────────────────────────────

function renderRootCauses(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const rootCauses = Array.isArray(report.rootCauses) ? report.rootCauses : [];
  const findings   = Array.isArray(report.findings)   ? report.findings   : [];

  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Root Cause Analysis", MARGIN, MARGIN + 2);
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(`${rootCauses.length} root cause${rootCauses.length !== 1 ? "s" : ""} identified`, PAGE_W - MARGIN - 120, MARGIN + 5, { width: 120, align: "right" });

  let y = MARGIN + 44;

  if (rootCauses.length === 0) {
    doc.font(F.regular).fontSize(9).fillColor(C.muted).text("No root causes identified. Ensure findings are present.", MARGIN, y);
    return;
  }

  rootCauses.forEach((rc, i) => {
    if (y > FOOTER_Y - 90) return;

    const color = severityColor(rc.severity);
    const impacts = Array.isArray(rc.operationalImpact) ? rc.operationalImpact.slice(0, 2) : [];
    const rowH    = 58 + impacts.length * 11;

    // Number circle
    doc.save()
      .circle(MARGIN + 10, y + 10, 10).fillColor(color).fill()
      .restore();
    doc.font(F.bold).fontSize(9).fillColor("#ffffff")
      .text(String(i + 1), MARGIN + 5, y + 5, { width: 12, align: "center" });

    // Severity badge
    severityBadge(doc, MARGIN + 26, y, safeText(rc.severity), color);

    // Title
    doc.font(F.bold).fontSize(10).fillColor(C.ink)
      .text(trunc(safeText(rc.title), 80), MARGIN + 26, y + 14, { width: CONTENT_W - 120 });

    // Confidence (right)
    confBar(doc, CONTENT_W - 30, y + 8, 80, rc.confidence ?? 0, color);
    doc.font(F.regular).fontSize(7).fillColor(color)
      .text(`${rc.confidence ?? 0}%`, CONTENT_W - 30, y + 16, { width: 80 });

    // Summary
    doc.font(F.regular).fontSize(8).fillColor(C.body)
      .text(trunc(safeText(rc.summary), 150), MARGIN + 26, y + 28, { width: CONTENT_W - 90 });

    // Contributing findings
    const linked = (rc.contributingFindings ?? [])
      .map(fid => findings.find(f => f.id === fid)?.title ?? fid)
      .filter(Boolean)
      .slice(0, 3)
      .join("  ·  ");
    if (linked) {
      doc.font(F.regular).fontSize(7).fillColor(C.muted)
        .text(`Contributing: ${trunc(linked, 120)}`, MARGIN + 26, y + 44, { width: CONTENT_W - 90 });
    }

    // Operational impacts
    let iy = y + (linked ? 57 : 44);
    impacts.forEach(imp => {
      doc.font(F.oblique).fontSize(7.5).fillColor(C.muted)
        .text(`• ${trunc(imp, 110)}`, MARGIN + 26, iy, { width: CONTENT_W - 90 });
      iy += 11;
    });

    rule(doc, y + rowH, "#f1f5f9");
    y += rowH + 6;
  });
}

// PAGE 6 — Priority Recommendations ───────────────────────────────────────────

function renderRecommendations(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const recs = Array.isArray(report.recommendations) ? report.recommendations : [];

  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Priority Recommendations", MARGIN, MARGIN + 2);
  doc.font(F.regular).fontSize(8).fillColor(C.coverMuted)
    .text(`${recs.length} action${recs.length !== 1 ? "s" : ""}`, PAGE_W - MARGIN - 80, MARGIN + 5, { width: 80, align: "right" });

  let y = MARGIN + 44;

  if (recs.length === 0) {
    doc.font(F.regular).fontSize(9).fillColor(C.muted).text("No recommendations generated. Ensure findings and root causes are present.", MARGIN, y);
    return;
  }

  TIMEFRAME_ORDER.forEach(tf => {
    const group = recs.filter(r => r.timeframe === tf);
    if (!group.length) return;
    if (y > FOOTER_Y - 40) return;

    // Timeframe header
    fillRect(doc, MARGIN - 4, y - 2, CONTENT_W + 8, 18, C.ink);
    doc.font(F.bold).fontSize(8.5).fillColor(C.coverText)
      .text(safeText(TIMEFRAME_LABELS[tf], tf).toUpperCase(), MARGIN + 4, y + 3, { characterSpacing: 1 });
    doc.font(F.regular).fontSize(7).fillColor(C.coverMuted)
      .text(`${group.length} recommendation${group.length !== 1 ? "s" : ""}`, MARGIN + CONTENT_W - 80, y + 3, { width: 80, align: "right" });
    y += 22;

    group.forEach((rec) => {
      if (y > FOOTER_Y - 60) return;

      const color     = priorityColor(rec.priority);
      const impacts   = (rec.expectedOperationalImpact ?? []).slice(0, 2);
      const actions   = (rec.actionItems ?? []).slice(0, 3);
      const rowH      = 44 + Math.max(impacts.length, actions.length) * 10;

      // Priority badge
      severityBadge(doc, MARGIN, y, safeText(rec.priority), color);

      // Difficulty
      doc.font(F.regular).fontSize(7).fillColor(C.muted)
        .text(`Effort: ${safeText(rec.implementationDifficulty)}`, MARGIN + 68, y);

      // Title
      doc.font(F.bold).fontSize(9.5).fillColor(C.ink)
        .text(trunc(safeText(rec.title), 80), MARGIN, y + 14, { width: CONTENT_W - 90 });

      // Confidence bar
      confBar(doc, CONTENT_W - 30, y + 8, 80, rec.confidence ?? 0, color);
      doc.font(F.regular).fontSize(7).fillColor(color)
        .text(`${rec.confidence ?? 0}%`, CONTENT_W - 30, y + 16, { width: 80 });

      // Summary
      doc.font(F.regular).fontSize(7.5).fillColor(C.body)
        .text(trunc(safeText(rec.summary), 120), MARGIN, y + 28, { width: CONTENT_W - 95 });

      // Two columns: actions vs impacts
      let ly = y + 42;
      const colW = (CONTENT_W - 10) / 2;
      if (actions.length > 0) {
        doc.font(F.bold).fontSize(7).fillColor(C.muted).text("Action Items", MARGIN, ly);
        actions.forEach((a, ai) => {
          doc.font(F.regular).fontSize(7).fillColor(C.body)
            .text(`${ai + 1}. ${trunc(a, 55)}`, MARGIN, ly + 10 + ai * 10, { width: colW - 10 });
        });
      }
      if (impacts.length > 0) {
        doc.font(F.bold).fontSize(7).fillColor(C.muted).text("Expected Impact", MARGIN + colW + 10, ly);
        impacts.forEach((imp, ii) => {
          doc.font(F.regular).fontSize(7).fillColor(C.healthy)
            .text(`✓ ${trunc(imp, 55)}`, MARGIN + colW + 10, ly + 10 + ii * 10, { width: colW - 10 });
        });
      }

      rule(doc, y + rowH, "#f1f5f9");
      y += rowH + 6;
    });

    y += 8;
  });
}

// PAGE 7 — Executive Narrative ────────────────────────────────────────────────

function renderNarrative(doc: PDFKit.PDFDocument, report: MGDReport): void {
  const { narrative } = report;

  fillRect(doc, 0, MARGIN - 10, PAGE_W, 34, C.sectionBg);
  doc.font(F.bold).fontSize(13).fillColor(C.coverText)
    .text("Executive Narrative", MARGIN, MARGIN + 2);

  let y = MARGIN + 44;

  const sections = [
    narrative?.executiveOverview,
    narrative?.operationalHealth,
    narrative?.strategicDirection,
    narrative?.finalConclusion,
  ].filter(Boolean);

  if (!sections.length) {
    doc.font(F.regular).fontSize(9).fillColor(C.muted).text("Narrative not available.", MARGIN, y);
    return;
  }

  sections.forEach(sec => {
    if (!sec || y > FOOTER_Y - 60) return;

    // Section label
    fillRect(doc, MARGIN - 4, y - 2, CONTENT_W + 8, 16, "#f1f5f9");
    doc.save().rect(MARGIN - 4, y - 2, 3, 16).fill(C.accent).restore();
    doc.font(F.bold).fontSize(9).fillColor(C.ink)
      .text(safeText(sec.title).toUpperCase(), MARGIN + 4, y + 2, { characterSpacing: 0.5 });
    y += 22;

    // Content text
    const content = safeText(sec.content);
    const lines   = doc.font(F.regular).fontSize(9).heightOfString(content, { width: CONTENT_W });
    doc.font(F.regular).fontSize(9).fillColor(C.body)
      .text(content, MARGIN, y, { width: CONTENT_W, lineGap: 3 });
    y += lines + 16;
    rule(doc, y - 4);
    y += 8;
  });
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Generate a premium executive operational diagnostic PDF from a MGDReport.
 * Returns a Buffer of the PDF binary.
 * Never throws — any page failure is caught and a fallback error page is written.
 */
export async function generateMGDPdfReport(report: MGDReport): Promise<Buffer> {
  console.log("[MGD][PDF] generateMGDPdfReport — start");
  const startedAt = Date.now();

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size:    "A4",
        margins: { top: MARGIN, bottom: MARGIN + 10, left: MARGIN, right: MARGIN },
        info: {
          Title:   `MGD Operational Diagnostic Report — ${safeText(report?.metadata?.clientName, "Client")}`,
          Author:  "MGD Operational Intelligence · Scope Optix Sdn. Bhd.",
          Subject: "Operational Diagnostic Report",
          Keywords:"MGD, operational intelligence, root cause, benchmarks, recommendations",
          Creator: "MGD-V1",
        },
        autoFirstPage: false,
      });

      const chunks: Buffer[] = [];
      doc.on("data",  chunk => chunks.push(chunk));
      doc.on("error", err   => { console.error("[MGD][PDF] PDFKit stream error:", err); reject(err); });
      doc.on("end",   ()    => {
        const buf = Buffer.concat(chunks);
        console.log(`[MGD][PDF] Complete — ${buf.length} bytes, ${Date.now() - startedAt}ms`);
        resolve(buf);
      });

      const TOTAL_PAGES = 7;
      const pages: Array<{ name: string; fn: (doc: PDFKit.PDFDocument, report: MGDReport) => void }> = [
        { name: "Cover",            fn: renderCover          },
        { name: "Summary",          fn: renderSummary        },
        { name: "Benchmarks",       fn: renderBenchmarks     },
        { name: "Findings",         fn: renderFindings       },
        { name: "Root Causes",      fn: renderRootCauses     },
        { name: "Recommendations",  fn: renderRecommendations },
        { name: "Narrative",        fn: renderNarrative      },
      ];

      pages.forEach((page, i) => {
        const pageNum = i + 1;
        doc.addPage();
        console.log(`[MGD][PDF] Rendering page ${pageNum}/${TOTAL_PAGES} — ${page.name}`);
        try {
          page.fn(doc, report);
        } catch (err) {
          console.error(`[MGD][PDF] Page ${pageNum} (${page.name}) render error:`, err);
          doc.font(F.regular).fontSize(9).fillColor(C.critical)
            .text(`[Page render error — ${page.name}]`, MARGIN, MARGIN + 50);
        }
        addFooter(doc, pageNum, TOTAL_PAGES);
      });

      doc.end();

      console.log(
        `[MGD][PDF] Pages rendered: ${pages.length}, ` +
        `findings=${report?.findings?.length ?? 0}, ` +
        `rootCauses=${report?.rootCauses?.length ?? 0}, ` +
        `recommendations=${report?.recommendations?.length ?? 0}, ` +
        `benchmarks=${report?.benchmarks?.length ?? 0}`,
      );
    } catch (err) {
      console.error("[MGD][PDF] Fatal error:", err);
      reject(err);
    }
  });
}
