import { describe, it, expect, vi } from "vitest";

// See mgd-pipeline-evidence.test.ts for why pipeline-trace is stubbed.
vi.mock("../pipeline-trace", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../pipeline-trace")>();
  return {
    ...actual,
    startTrace: vi.fn(async () => ({ traceId: "test-trace", createdAt: new Date().toISOString(), steps: [], status: "running" as const })),
    addTraceStep: vi.fn(async () => null),
    completeTrace: vi.fn(async () => null),
  };
});

import { runMGDPipeline } from "../mgd-pipeline.js";
import { FINDING_CATEGORIES } from "../findings-engine.js";
import { REC_CATEGORIES } from "../recommendation-engine.js";

// ─────────────────────────────────────────────────────────────────────────────
// Regression coverage for docs/MGD_DIAGNOSTIC_SCOPE_EVIDENCE_COVERAGE_ADR.md.
// This milestone concluded that no safe, deterministic scope→evidence
// correlation exists today, and implemented NONE. These tests exist to (a)
// preserve every current diagnosticScope/business-concern invariant
// established by prior milestones, and (b) codify, as executable facts, the
// specific architectural findings this milestone's conclusion rests on — so
// a future change that silently unifies the category vocabularies (which
// would reopen the correlation question) does not pass silently.
// ─────────────────────────────────────────────────────────────────────────────

const REAL_TRANSACTIONS = Array.from({ length: 10 }, (_, i) => ({
  documentId: "doc-1",
  transactionType: "dispatch_event",
  rawText: `Dispatch Complete?: ${i % 3 === 0 ? "No" : "Yes"}`,
  quantity: 10,
  entityName: "Event Alpha",
}));

describe("Architecture fact: Finding categories and Recommendation categories are NOT the same vocabulary", () => {
  it("only warehouse_operations is a literal string match between the two category sets — every other pair differs", () => {
    const findingCats = new Set(Object.values(FINDING_CATEGORIES));
    const recCats = new Set(Object.values(REC_CATEGORIES));
    const intersection = [...findingCats].filter(c => recCats.has(c as any));
    expect(intersection).toEqual(["warehouse_operations"]);
    // This is the concrete basis for this milestone's conclusion that
    // "category" cannot serve as a single, stable evidence-coverage domain
    // anchor without a translation step that itself requires judgment.
  });
});

describe("Architecture fact: RootCause carries no category of its own", () => {
  it("RootCause objects are cross-category syntheses, not single-domain — contributingFindings can span multiple finding categories", async () => {
    const result = await runMGDPipeline({
      clientName: "Real Evidence Co.", industry: "event_management",
      transactions: REAL_TRANSACTIONS, documents: [{ id: "doc-1", fileName: "dispatches.xlsx" }],
    });
    expect(result.report.rootCauses.length).toBeGreaterThan(0);
    for (const rc of result.report.rootCauses) {
      expect(rc).not.toHaveProperty("category");
    }
  });
});

describe("A concern lexically matching an existing category name still never earns SUPPORTED/NOT_SUPPORTED (Phase 5 epistemic test, in code)", () => {
  it("a concern whose text names a real finding category verbatim is still only ever UNVALIDATED or INSUFFICIENT_EVIDENCE — mere lexical overlap is not correlation", async () => {
    const base = {
      clientName: "Real Evidence Co.", industry: "event_management",
      transactions: REAL_TRANSACTIONS, documents: [{ id: "doc-1", fileName: "dispatches.xlsx" }],
    };
    const withMatchingConcern = await runMGDPipeline({
      ...base,
      // Deliberately reuses the exact category label MGD itself would
      // produce for this dataset (dispatch_operations findings ARE
      // generated by REAL_TRANSACTIONS) — the strongest possible case for a
      // naive "it matches, so it must be supported" shortcut.
      businessConcerns: ["dispatch_operations"],
    });
    const withUnrelatedConcern = await runMGDPipeline({
      ...base,
      businessConcerns: ["Client is worried about an entirely unrelated topic."],
    });

    expect(withMatchingConcern.report.diagnosticScope![0].status).toBe("UNVALIDATED");
    expect(withUnrelatedConcern.report.diagnosticScope![0].status).toBe("UNVALIDATED");
    // Identical status regardless of lexical overlap — proves no matching,
    // scoring, or correlation logic runs today, exactly as designed.
    expect(withMatchingConcern.report.diagnosticScope![0].status)
      .toBe(withUnrelatedConcern.report.diagnosticScope![0].status);

    // And, as ever, the analytical output itself is completely unaffected.
    expect(withMatchingConcern.report.findings).toEqual(withUnrelatedConcern.report.findings);
  });
});

describe("Preservation — all prior-milestone diagnosticScope/business-concern invariants remain exactly as before", () => {
  it("business concerns still do not affect findings, root causes, recommendations, benchmarks, health score, or evidence sufficiency", async () => {
    const base = {
      clientName: "Real Evidence Co.", industry: "event_management",
      transactions: REAL_TRANSACTIONS, documents: [{ id: "doc-1", fileName: "dispatches.xlsx" }],
    };
    const [without, withConcern] = await Promise.all([
      runMGDPipeline(base),
      runMGDPipeline({ ...base, businessConcerns: ["Client is concerned about delivery delays."] }),
    ]);
    expect(withConcern.report.findings).toEqual(without.report.findings);
    expect(withConcern.report.rootCauses).toEqual(without.report.rootCauses);
    expect(withConcern.report.recommendations).toEqual(without.report.recommendations);
    expect(withConcern.report.benchmarks).toEqual(without.report.benchmarks);
    expect(withConcern.steps.healthScore).toBe(without.steps.healthScore);
    expect(withConcern.steps.evidence).toEqual(without.steps.evidence);
  });

  it("no concern ever becomes FindingEvidence", async () => {
    const result = await runMGDPipeline({
      clientName: "Real Evidence Co.", industry: "event_management",
      transactions: REAL_TRANSACTIONS, documents: [{ id: "doc-1", fileName: "dispatches.xlsx" }],
      businessConcerns: ["Client is concerned about delivery delays."],
    });
    const allEvidenceText = result.report.findings
      .flatMap(f => f.evidence ?? [])
      .map(e => `${e.observation} ${e.source ?? ""}`)
      .join(" ").toLowerCase();
    expect(allEvidenceText).not.toMatch(/delivery delays/);
  });

  it("no unsupported scope status is ever fabricated, across NONE/PARTIAL/SUFFICIENT evidence", async () => {
    const scenarios = [
      { transactions: [], documents: [] }, // NONE
      { transactions: REAL_TRANSACTIONS.slice(0, 2), documents: [{ id: "doc-1", fileName: "x.xlsx" }] }, // PARTIAL (below floor)
      { transactions: REAL_TRANSACTIONS, documents: [{ id: "doc-1", fileName: "dispatches.xlsx" }] }, // SUFFICIENT
    ];
    for (const scenario of scenarios) {
      const result = await runMGDPipeline({
        clientName: "Test Co.", industry: "event_management",
        businessConcerns: ["A stated concern."], ...scenario,
      });
      const status = result.report.diagnosticScope![0].status;
      expect(["UNVALIDATED", "INSUFFICIENT_EVIDENCE"]).toContain(status);
    }
  });

  it("existing reports without diagnosticScope remain compatible", () => {
    const oldReport: any = { metadata: { generatedAt: "2026-01-01T00:00:00.000Z", reportVersion: "MGD-V1" }, findings: [] };
    expect(oldReport.diagnosticScope).toBeUndefined();
    expect(oldReport.diagnosticScope?.length ?? 0).toBe(0);
  });
});
